# Classification

## Cleaning and Splitting (copied from initial_exploration)

In [7]:
'''
import pandas as pd
df = pd.read_csv("suiciderates.csv")

#Making generations boolean
df_split_gen = df.copy()

def gen_x_bool(gen):
    if gen == "Generation X":
        return 1
    else:
        return 0

df_split_gen["Generation X"] = df_split_gen["generation"].map(gen_x_bool)

def silent_bool(gen):
    if gen == "Silent":
        return 1
    else:
        return 0

df_split_gen["Silent"] = df_split_gen["generation"].map(silent_bool)

def mil_bool(gen):
    if gen == "Millenials":
        return 1
    else:
        return 0

df_split_gen["Millenials"] = df_split_gen["generation"].map(mil_bool)

def boom_bool(gen):
    if gen == "Boomers":
        return 1
    else:
        return 0

df_split_gen["Boomers"] = df_split_gen["generation"].map(boom_bool)

def g_i_bool(gen):
    if gen == "G.I. Generation":
        return 1
    else:
        return 0

df_split_gen["G.I. Generation"] = df_split_gen["generation"].map(g_i_bool)

def z_bool(gen):
    if gen == "Generation Z":
        return 1
    else:
        return 0

df_split_gen["Generation Z"] = df_split_gen["generation"].map(z_bool)

# Drop the original generation column
drop_gen = df_split_gen.copy()
drop_gen.drop(labels="generation", axis='columns', inplace=True)

# Changing sex to a boolean
df_sex = drop_gen.copy()
df_sex["sex"].replace("female", 0,inplace=True)
df_sex["sex"].replace("male", 1, inplace=True)

# Rename it to male for easier understanding
df_sex.rename(columns = {'sex':'male'}, inplace = True)

# Changing age to a boolean
age_bool = df_sex.copy()

def g1_bool(age):
    if age == "5-14 years":
        return 1
    else:
        return 0

age_bool["5-14 years"] = age_bool["age"].map(g1_bool)

def g2_bool(age):
    if age == "15-24 years":
        return 1
    else:
        return 0

age_bool["15-24 years"] = age_bool["age"].map(g2_bool)

def g3_bool(age):
    if age == "25-34 years":
        return 1
    else:
        return 0

age_bool["25-34 years"] = age_bool["age"].map(g3_bool)

def g4_bool(age):
    if age == "35-54 years":
        return 1
    else:
        return 0

age_bool["35-54 years"] = age_bool["age"].map(g4_bool)

def g5_bool(age):
    if age == "55-74 years":
        return 1
    else:
        return 0

age_bool["55-74 years"] = age_bool["age"].map(g5_bool)

def g6_bool(age):
    if age == "75+ years":
        return 1
    else:
        return 0

age_bool["75+ years"] = age_bool["age"].map(g6_bool)

# Drop HDI for year
drop_hdi = age_bool.copy()
drop_hdi.drop(labels="HDI for year", axis='columns', inplace=True)

# Convert GDP to numerical values
gdp_to_num = drop_hdi.copy()
# rename the columns due to formatting issues
new_cols = gdp_to_num.columns.values
new_cols[8] = 'gdp_for_year $'
new_cols[9] = 'gdp_per_capita $'
gdp_to_num.columns = new_cols

#Change the datatype of gdp_for_year
gdp_to_num['gdp_for_year $'] = gdp_to_num.iloc[:,8].str.replace(',', '').astype(float)

from sklearn.model_selection import train_test_split

data2 = gdp_to_num.copy()
train_set, test_set = train_test_split(data2, test_size=0.2, random_state=123)
print("traning set length:", len(train_set),"\ntest set length:", len(test_set))
print(data2.info())'''

import pandas as pd
df = pd.read_csv("suiciderates.csv")

#Making generations boolean
df_split_gen = df.copy()

def gen_x_bool(gen):
    if gen == "Generation X":
        return 1
    else:
        return 0

df_split_gen["Generation X"] = df_split_gen["generation"].map(gen_x_bool)

def silent_bool(gen):
    if gen == "Silent":
        return 1
    else:
        return 0

df_split_gen["Silent"] = df_split_gen["generation"].map(silent_bool)

def mil_bool(gen):
    if gen == "Millenials":
        return 1
    else:
        return 0

df_split_gen["Millenials"] = df_split_gen["generation"].map(mil_bool)

def boom_bool(gen):
    if gen == "Boomers":
        return 1
    else:
        return 0

df_split_gen["Boomers"] = df_split_gen["generation"].map(boom_bool)

def g_i_bool(gen):
    if gen == "G.I. Generation":
        return 1
    else:
        return 0

df_split_gen["G.I. Generation"] = df_split_gen["generation"].map(g_i_bool)

def z_bool(gen):
    if gen == "Generation Z":
        return 1
    else:
        return 0

df_split_gen["Generation Z"] = df_split_gen["generation"].map(z_bool)


# Changing sex to a boolean
df_sex = df_split_gen.copy()
df_sex["sex"].replace("female", 0,inplace=True)
df_sex["sex"].replace("male", 1, inplace=True)

# Rename it to male for easier understanding
df_sex.rename(columns = {'sex':'male'}, inplace = True)

# Changing age to a boolean
age_bool = df_sex.copy()

def g1_bool(age):
    if age == "5-14 years":
        return 1
    else:
        return 0

age_bool["5-14 years"] = age_bool["age"].map(g1_bool)

def g2_bool(age):
    if age == "15-24 years":
        return 1
    else:
        return 0

age_bool["15-24 years"] = age_bool["age"].map(g2_bool)

def g3_bool(age):
    if age == "25-34 years":
        return 1
    else:
        return 0

age_bool["25-34 years"] = age_bool["age"].map(g3_bool)

def g4_bool(age):
    if age == "35-54 years":
        return 1
    else:
        return 0

age_bool["35-54 years"] = age_bool["age"].map(g4_bool)

def g5_bool(age):
    if age == "55-74 years":
        return 1
    else:
        return 0

age_bool["55-74 years"] = age_bool["age"].map(g5_bool)

def g6_bool(age):
    if age == "75+ years":
        return 1
    else:
        return 0

age_bool["75+ years"] = age_bool["age"].map(g6_bool)


# Convert GDP to numerical values
gdp_to_num = age_bool.copy()
# rename the columns due to formatting issues
new_cols = gdp_to_num.columns.values
new_cols[8] = 'gdp_for_year $'
new_cols[9] = 'gdp_per_capita $'
gdp_to_num.columns = new_cols

#Change the datatype of gdp_for_year
#gdp_to_num['gdp_for_year $'] = gdp_to_num.iloc[:,8].str.replace(',', '').astype(float)

from sklearn.model_selection import train_test_split

data2 = gdp_to_num.copy()
train_set, test_set = train_test_split(data2, test_size=0.2, random_state=123)
print("traning set length:", len(train_set),"\ntest set length:", len(test_set))
print(data2.info())

traning set length: 22256 
test set length: 5564
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27820 entries, 0 to 27819
Data columns (total 24 columns):
country               27820 non-null object
year                  27820 non-null int64
male                  27820 non-null int64
age                   27820 non-null object
suicides_no           27820 non-null int64
population            27820 non-null int64
suicides/100k pop     27820 non-null float64
country-year          27820 non-null object
gdp_for_year $        8364 non-null float64
gdp_per_capita $      27820 non-null object
gdp_per_capita ($)    27820 non-null int64
generation            27820 non-null object
Generation X          27820 non-null int64
Silent                27820 non-null int64
Millenials            27820 non-null int64
Boomers               27820 non-null int64
G.I. Generation       27820 non-null int64
Generation Z          27820 non-null int64
5-14 years            27820 non-null int64
15-24 years      

## Initial Features:
- I am going to choose population for X because that will be the best estimator to distinguish between countries. I will choose suicide_no for Y again.

## Decision Tree

In [2]:
from sklearn.tree import DecisionTreeClassifier
X = train_set[["population"]]
y = train_set["suicides_no"]

tree_classifier = DecisionTreeClassifier()
tree_classifier.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

### Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix
y_predicted = tree_classifier.predict(X)
matrix = confusion_matrix(y, y_predicted)
print(matrix)

[[1552  532  232 1022  155  216]
 [ 938 1174  248  943  160  215]
 [ 828  539 1137  810  210  190]
 [ 471  295   22 2780   25  117]
 [ 821  544  353 1033  783  170]
 [ 781  523  256 1540  142  499]]


### Comments
- The confusion matrix is too large to tell for certain, but it seems like this is a decent confusion matrix.

### Accuracy, Precision, Sensitivity, F1

In [22]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print ("Accuracy: ", accuracy_score(y, y_predicted))
print ("Precision: ", precision_score(y, y_predicted, average="weighted"))
print ("Sensitivity: ", recall_score(y, y_predicted, average="weighted"))
print ("F1: ", f1_score(y, y_predicted, average="weighted"))

Accuracy:  0.35608375269590226
Precision:  0.3911442799823402
Sensitivity:  0.35608375269590226
F1:  0.334960421566664


### Comments
- These are all really good values, but it makes me skeptical that there could be over-fitting.

In [5]:
from sklearn.model_selection import KFold
validation_accuracy = []
validation_f1 =[]
fold_and_validate = KFold(n_splits=5, shuffle=True, random_state=145)
for train_set_indices, validation_set_indices in fold_and_validate.split(X):
    cv_train_set = X.iloc[train_set_indices]
    cv_train_target = y.iloc[train_set_indices]
    
    cv_decision_tree = DecisionTreeClassifier()
    cv_decision_tree.fit(cv_train_set, cv_train_target)
    
    cv_xvalidation = X.iloc[validation_set_indices]
    cv_y_true = y.iloc[validation_set_indices]
    cv_y_predicted = cv_decision_tree.predict(cv_xvalidation)
    
    cv_accuracy_score = accuracy_score(cv_y_true, cv_y_predicted)
    cv_f1_score = f1_score(cv_y_true, cv_y_predicted,  average="weighted")
    validation_accuracy.append(cv_accuracy_score)
    validation_f1.append(cv_f1_score)
    
print("Cross validation accuracies are: ", validation_accuracy)
print("Cross validation f1 scores  are: ", validation_f1)
    


C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', a

Cross validation accuracies are:  [0.10242587601078167, 0.10604358571107617, 0.09683217254549539, 0.09862952145585262, 0.09638283531790609]
Cross validation f1 scores  are:  [0.09772587965647832, 0.10391650511121436, 0.09241915286671885, 0.09418498795039965, 0.09388090523114796]


C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


## KNN: K-Nearest Neighbours Classifier

In [27]:
# help from: https://www.geeksforgeeks.org/multiclass-classification-using-scikit-learn/
# importing necessary libraries 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
  
X = train_set[["population"]]
y = train_set["suicides_no"]

# dividing X, y into train and test data 
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 123) 
  
# training a KNN classifier 
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train, y_train) 

In [28]:
from sklearn.metrics import confusion_matrix
knn_predicted = knn.predict(X_test)
matrix = confusion_matrix(y_test, knn_predicted)
print(matrix)

[[694  54  29 ...   0   0   0]
 [204  32  28 ...   0   0   0]
 [121  32  20 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [29]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print ("Accuracy: ", accuracy_score(y_test, knn_predicted))
print ("Precision: ", precision_score(y_test, knn_predicted, average="weighted"))
print ("Sensitivity: ", recall_score(y_test, knn_predicted, average="weighted"))
print ("F1: ", f1_score(y_test, knn_predicted, average="weighted"))

Accuracy:  0.1419841840402588
Precision:  0.06653485304275338
Sensitivity:  0.1419841840402588
F1:  0.08959923481091099


C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', 

### Comments
- This classifier was much worse. None of the tests came out well.

## Naive Bayes Classifier 

In [35]:
# importing necessary libraries 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
  
X = train_set[["population"]]
y = train_set["suicides_no"]
  
# dividing X, y into train and test data 
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 123) 
  
# training a Naive Bayes classifier 
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB().fit(X_train, y_train) 
gnb_predicted = gnb.predict(X_test) 

In [36]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y_test, gnb_predicted)
print(matrix)

[[856   0   0 ...   0   0   0]
 [303   0   2 ...   0   0   0]
 [222   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [37]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print ("Accuracy: ", accuracy_score(y_test, knn_predicted))
print ("Precision: ", precision_score(y_test, knn_predicted, average="weighted"))
print ("Sensitivity: ", recall_score(y_test, knn_predicted, average="weighted"))
print ("F1: ", f1_score(y_test, knn_predicted, average="weighted"))

Accuracy:  0.1419841840402588
Precision:  0.06653485304275338
Sensitivity:  0.1419841840402588
F1:  0.08959923481091099


C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', 

### Comments
- This classifier was also not great. The tests were all very low and the matrix was not good. The original decision tree was the best.

## Final Evaluation

In [32]:
from sklearn.tree import DecisionTreeClassifier
X = test_set[["population"]]
y = test_set["suicides_no"]

tree_classifier = DecisionTreeClassifier()
tree_classifier.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [33]:
from sklearn.metrics import confusion_matrix
y_predicted = tree_classifier.predict(X)
matrix = confusion_matrix(y, y_predicted)
print(matrix)

[[851   0   0 ...   0   0   0]
 [ 10 310   0 ...   0   0   0]
 [  4   2 210 ...   0   0   0]
 ...
 [  0   0   0 ...   1   0   0]
 [  0   0   0 ...   0   1   0]
 [  0   0   0 ...   0   0   1]]


In [34]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print ("Accuracy: ", accuracy_score(y, y_predicted))
print ("Precision: ", precision_score(y, y_predicted, average="weighted"))
print ("Sensitivity: ", recall_score(y, y_predicted, average="weighted"))
print ("F1: ", f1_score(y, y_predicted, average="weighted"))

Accuracy:  0.9849029475197699
Precision:  0.9848352094930028
Sensitivity:  0.9849029475197699
F1:  0.9845516220486507


C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\s523286\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### Comments
- The test set was even better than the training set. This was a good model.

## Trying Different Features

In [19]:
from sklearn.tree import DecisionTreeClassifier
X = train_set[["suicides_no"]]
y = train_set["age"]

tree_classifier = DecisionTreeClassifier()
tree_classifier.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [23]:
import numpy as np
import matplotlib.pyplot as plt
plt.scatter(train_set["suicides_no"], train_set["age"], color="red")
plt.xlabel("suicides num)")
plt.ylabel("age")
plt.show()


### Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix
y_predicted = tree_classifier.predict(X)
matrix = confusion_matrix(y, y_predicted)
print(matrix)

[[1552  532  232 1022  155  216]
 [ 938 1174  248  943  160  215]
 [ 828  539 1137  810  210  190]
 [ 471  295   22 2780   25  117]
 [ 821  544  353 1033  783  170]
 [ 781  523  256 1540  142  499]]


### Comments
- 